@startuml webクラス図
skinparam ClassAttributeFontSize 0
class web{
 -ユーザID
 -名前
 -パスワード
 -学校名
 -所属名
 -メールアドレス
 -電話番号
 -年齢
 

 +登録する()
 +参照する()
 +変更する()
 +削除する()
 +ログイン()
 +ログアウト()

 }
 
 
' 12345
' 12345
' 12345
' 12345      
@enduml
