@startuml Web訪問者ドメインモデル図
skinparam componentStyle rectangle

' 訪問者
[Webページ] o-- [ユーザ]
[ユーザ] o-- [ユーザID]
[ユーザ] o-- [パスワード]
[ユーザ] o-- [名前]
[ユーザ] o-- [学校名]
[ユーザ] o-- [所属名]
[ユーザ] o-- [メールアドレス]
[ユーザ] o-- [電話番号]
[ユーザ] o-- [年齢]




@enduml