@startuml 顧客
skinparam classAttributeIconSize 0

class 顧客 {
  - 顧客ID
  - 名前
  - 住所
  - 電話番号
  - メールアドレス
  - クレジットカード情報
  - 伝票
  - 数量
  - 金額
  - 状態（注文済・発送中・発送完了・キャンセル申請中）
  --
  + ログイン()
  + ログアウト()
  + 商品購入()
  + 返品手続き()
  + 一覧を確認()
  + クレジットカード選択()
  + 利用者情報送付()
}

@enduml