@startuml bbショップドメインモデル図
skinparam componentStyle rectangle

[管理者] o-- [管理者ID] 
[管理者] -- [注文履歴] 
[管理者] -- [返品]
[顧客] o-- [ユーザーID] 
[顧客] o-- [パスワード] 
[顧客] o-- [氏名] 
[顧客] o-- [住所] 
[顧客] o-- [メールアドレス] 
[顧客] o-- [電話番号] 
[顧客] o-- [クレジット情報] 

[注文履歴] o-- [決済金額]
[注文履歴] o-- [注文ID]
[注文履歴] o-- [注文日時]
[注文履歴] o-- [注文詳細]


[カート] o-- [取扱商品] 
[カート] o-- [数量] 
[注文] o-- [合計金額] 
[カート] -- [商品] 
[注文] o-- [注文番号] 
[注文] o-- [注文日] 
[注文] -- [カート] 
[注文] -- [顧客] 

[返品] o-- [返品理由]
[返品] o-- [返品ID]
[返品] o-- [返品日時]
[返品] o-- [商品名]
[返品] -- [返金]
[商品] o-- [商品ID] 
[商品] o-- [商品情報] 
[商品] o-- [在庫数] 

[返金] o-- [返金金額]
[返金] o-- [注文ID]






@enduml

