@startuml Web訪問者ドメインモデル図
skinparam componentStyle rectangle

' 会議

[ユーザ] o-- [ユーザID]
[会議室名] o-- [座席数]
[会議室名] o-- [AV機器の有無]
[ユーザ] o-- [名前]
[会議室名] o-- [予約番号]
[会議室名] o-- [利用会議室]
[会議室名] o-- [利用時刻]
[会議室名] o-- [利用目的]





@enduml