@startuml Robodogクラス図
skinparam classAttributeIconSize 0
hide circle

class RoboDog {
 -myName:String
 -myTime:int
 -goodMorning:String
 -goodAfternoon :String
 -goodNight:String
 -firstValue:int
 -secondValue:int
 -result:int

 +getMyName():String
 +setNewName():int
 +setNewTime():void
 +getMyGreeting():String
 +setTwoValues():void
 +setAndGetResult():void
 +getAddition():int
}

@enduml
