@startuml Robodogクラス図
skinparam classAttributeIconSize 0
hide circle

class RoboDog {
 -myName
 -myTime
 -goodMorning
 -goodAfternoon 
 -goodNight
 -firstValue
 -secondValue
 -result

 +getMyName()
 +setMyName()
 +setNewTime()
 +getMyGreeting()
 +setTwoValues()
 +setAndGetResult()
}

@enduml
